apiVersion: datasciencecluster.opendatahub.io/v2
kind: DataScienceCluster
metadata:
  name: default-dsc
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  components:

    dashboard:
      managementState: Managed

    workbenches:
      managementState: Managed
      workbenchNamespace: rhods-notebooks

    kserve:
      managementState: Managed
      rawDeploymentServiceConfig: Headless

      nim:
        managementState: Managed

    modelregistry:
      managementState: Managed
      registriesNamespace: rhoai-model-registries

    feastoperator:
      managementState: Managed

    trustyai:
      managementState: Managed
      eval:
        lmeval:
          permitCodeExecution: deny
          permitOnline: deny

    aipipelines:
      managementState: Managed

    ray:
      managementState: Managed

    trainingoperator:
      managementState: Managed

    trainer:
      managementState: Removed

    mlflowoperator:
      managementState: Removed

    llamastackoperator:
      managementState: Removed

    kueue:
      managementState: Removed
      defaultClusterQueueName: default
      defaultLocalQueueName: default