apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: default-dsc
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  components:

    kserve:
      managementState: Managed
      nim:
        managementState: Managed
      rawDeploymentServiceConfig: Headless

    modelregistry:
      managementState: Managed
      registriesNamespace: rhoai-model-registries

    feastoperator:
      managementState: Managed

    trustyai:
      managementState: Managed
      eval:
        lmeval:
          permitCodeExecution: deny
          permitOnline: deny

    aipipelines:
      managementState: Managed

    ray:
      managementState: Managed

    kueue:
      defaultClusterQueueName: default
      defaultLocalQueueName: default
      managementState: Removed

    workbenches:
      managementState: Managed
      workbenchNamespace: rhods-notebooks

    mlflowoperator:
      managementState: Removed

    dashboard:
      managementState: Managed

    trainer: {}
    
    llamastackoperator:
      managementState: Removed

    trainingoperator:
      managementState: Managed