apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: default-dsc
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

spec:
  components:
    codeflare:
      managementState: Removed

    kserve:
      defaultDeploymentMode: RawDeployment
      managementState: Managed
      serving:
        managementState: Removed
        name: knative-serving

    modelregistry:
      registriesNamespace: rhoai-model-registries

    feastoperator: {}

    trustyai:
      managementState: Removed

    ray:
      managementState: Managed

    kueue:
      managementState: Removed

    workbenches:
      managementState: Managed

    dashboard:
      managementState: Managed

    modelmeshserving:
      managementState: Removed

    llamastackoperator: {}

    datasciencepipelines:
      managementState: Managed

    trainingoperator:
      managementState: Managed
