apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-patch-sa
  namespace: openshift-gitops

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-patch-clusterrole
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["argocds"]
    verbs: ["get", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-patch-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: argocd-patch-sa
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-patch-clusterrole